// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925093434_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Snake"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tetris"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brick Breaker"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brick Breaker 2"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goal Scorer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Super Bricks"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$11$rn.FwhrTjNC7E9O3Fk3nm.3CEY.wIZKqbBK6rpWXdPs6tBGoxgueW",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "test_user_c_sharp"
                        },
                        new
                        {
                            Id = 2,
                            Password = "$2a$11$7i6PP.C/M84I6FsFFFJS2eOKJlppUMAeEb6QzyJ4thZp1U5FEFYjK",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "emanuel"
                        },
                        new
                        {
                            Id = 3,
                            Password = "$2a$11$b1mfR7RAIB1VeHIAwu8Dn.zkS7WwJnIWrWzDzbsRvfEGd7bLFQAsy",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "emanuelco.07"
                        },
                        new
                        {
                            Id = 4,
                            Password = "$2a$11$hazM9eN4lNB2h0awMOXebOkAfWSdBMFFr4fjAbnE4Nx6EALpf2nVu",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "andrei"
                        },
                        new
                        {
                            Id = 5,
                            Password = "$2a$11$x40hWgbfhTmpkasJUwbLH.nEJoLTHP6kNUik203DUG.JVZw4xHm0G",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "final_boss"
                        },
                        new
                        {
                            Id = 6,
                            Password = "$2a$11$c2iv...by4i8jWxLj38nT.W9N3RiZpmAZaUIDEGBjcsjmLX31Jv.e ",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "vale"
                        },
                        new
                        {
                            Id = 7,
                            Password = "$2a$11$zhLty/lZixfjZERsRlPDQebGoEIlvKlS3ITUrJMFIMr.NbacbwECG",
                            RegistrationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "beni"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.UserGameScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("HighScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGameScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            HighScore = 80,
                            LastUpdated = new DateTime(2025, 9, 23, 11, 9, 51, 420, DateTimeKind.Unspecified).AddTicks(5300),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            HighScore = 2,
                            LastUpdated = new DateTime(2025, 7, 15, 14, 10, 17, 179, DateTimeKind.Unspecified).AddTicks(8280),
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            HighScore = 39,
                            LastUpdated = new DateTime(2025, 7, 28, 13, 30, 5, 335, DateTimeKind.Unspecified).AddTicks(2550),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            GameId = 1,
                            HighScore = 45,
                            LastUpdated = new DateTime(2025, 9, 23, 11, 14, 11, 813, DateTimeKind.Unspecified).AddTicks(990),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            GameId = 1,
                            HighScore = 1,
                            LastUpdated = new DateTime(2025, 7, 15, 14, 11, 25, 620, DateTimeKind.Unspecified).AddTicks(340),
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            GameId = 1,
                            HighScore = 4,
                            LastUpdated = new DateTime(2025, 7, 15, 14, 19, 15, 913, DateTimeKind.Unspecified).AddTicks(9630),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            GameId = 2,
                            HighScore = 28154,
                            LastUpdated = new DateTime(2025, 7, 24, 8, 43, 22, 392, DateTimeKind.Unspecified).AddTicks(4070),
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            GameId = 2,
                            HighScore = 204,
                            LastUpdated = new DateTime(2025, 7, 23, 9, 41, 58, 901, DateTimeKind.Unspecified).AddTicks(3020),
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            GameId = 2,
                            HighScore = 314,
                            LastUpdated = new DateTime(2025, 7, 24, 9, 42, 5, 747, DateTimeKind.Unspecified).AddTicks(8460),
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            GameId = 2,
                            HighScore = 194,
                            LastUpdated = new DateTime(2025, 7, 23, 9, 42, 57, 10, DateTimeKind.Unspecified).AddTicks(320),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            GameId = 2,
                            HighScore = 8412,
                            LastUpdated = new DateTime(2025, 8, 11, 13, 56, 8, 203, DateTimeKind.Unspecified).AddTicks(9570),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            GameId = 3,
                            HighScore = 6207,
                            LastUpdated = new DateTime(2025, 9, 19, 9, 57, 3, 365, DateTimeKind.Unspecified).AddTicks(4290),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            GameId = 3,
                            HighScore = 3456,
                            LastUpdated = new DateTime(2025, 8, 20, 11, 18, 45, 516, DateTimeKind.Unspecified).AddTicks(1550),
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            GameId = 3,
                            HighScore = 1100,
                            LastUpdated = new DateTime(2025, 8, 14, 11, 27, 1, 53, DateTimeKind.Unspecified).AddTicks(3870),
                            UserId = 6
                        },
                        new
                        {
                            Id = 15,
                            GameId = 3,
                            HighScore = 500,
                            LastUpdated = new DateTime(2025, 8, 19, 11, 33, 35, 830, DateTimeKind.Unspecified).AddTicks(8930),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            GameId = 3,
                            HighScore = 7014,
                            LastUpdated = new DateTime(2025, 8, 20, 12, 18, 5, 929, DateTimeKind.Unspecified).AddTicks(1480),
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            GameId = 4,
                            HighScore = 3430,
                            LastUpdated = new DateTime(2025, 8, 20, 11, 59, 40, 679, DateTimeKind.Unspecified).AddTicks(8820),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            GameId = 4,
                            HighScore = 5678,
                            LastUpdated = new DateTime(2025, 8, 20, 12, 44, 27, 665, DateTimeKind.Unspecified).AddTicks(2140),
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            GameId = 5,
                            HighScore = 20,
                            LastUpdated = new DateTime(2025, 8, 25, 14, 32, 2, 217, DateTimeKind.Unspecified).AddTicks(1260),
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            GameId = 5,
                            HighScore = 10,
                            LastUpdated = new DateTime(2025, 8, 25, 14, 34, 1, 880, DateTimeKind.Unspecified).AddTicks(6930),
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            GameId = 5,
                            HighScore = 20,
                            LastUpdated = new DateTime(2025, 8, 25, 14, 52, 3, 98, DateTimeKind.Unspecified).AddTicks(6460),
                            UserId = 6
                        },
                        new
                        {
                            Id = 22,
                            GameId = 6,
                            HighScore = 23500,
                            LastUpdated = new DateTime(2025, 9, 1, 13, 44, 24, 105, DateTimeKind.Unspecified).AddTicks(2200),
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            GameId = 6,
                            HighScore = 6500,
                            LastUpdated = new DateTime(2025, 9, 1, 13, 51, 15, 97, DateTimeKind.Unspecified).AddTicks(1270),
                            UserId = 6
                        },
                        new
                        {
                            Id = 24,
                            GameId = 6,
                            HighScore = 5700,
                            LastUpdated = new DateTime(2025, 9, 1, 14, 24, 29, 104, DateTimeKind.Unspecified).AddTicks(5250),
                            UserId = 3
                        },
                        new
                        {
                            Id = 25,
                            GameId = 6,
                            HighScore = 16894,
                            LastUpdated = new DateTime(2025, 9, 1, 14, 27, 31, 353, DateTimeKind.Unspecified).AddTicks(6610),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            GameId = 6,
                            HighScore = 19391,
                            LastUpdated = new DateTime(2025, 9, 1, 14, 29, 54, 950, DateTimeKind.Unspecified).AddTicks(4740),
                            UserId = 4
                        },
                        new
                        {
                            Id = 27,
                            GameId = 4,
                            HighScore = 6914,
                            LastUpdated = new DateTime(2025, 9, 22, 14, 46, 20, 926, DateTimeKind.Unspecified).AddTicks(8190),
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            GameId = 4,
                            HighScore = 6066,
                            LastUpdated = new DateTime(2025, 9, 22, 15, 14, 59, 684, DateTimeKind.Unspecified).AddTicks(5460),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.UserGameScore", b =>
                {
                    b.HasOne("WebApplication1.Models.Game", "Game")
                        .WithMany("UserGameScores")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("UserGameScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Game", b =>
                {
                    b.Navigation("UserGameScores");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("UserGameScores");
                });
#pragma warning restore 612, 618
        }
    }
}
